# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yor < Formula
  desc "Extensible auto-tagger for your IaC files"
  homepage "https://www.yor.io"
  version "0.1.168"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.168/yor_0.1.168_darwin_arm64.tar.gz"
      sha256 "b5d30ac0849398bedf0274e0e7c45151feb3eb290a198fd40215fc781e781985"

      def install
        bin.install "yor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.168/yor_0.1.168_darwin_amd64.tar.gz"
      sha256 "6f3069c4dd6218ccce983c55b7e3897a5ebf6170fd67d86930497cb92d41ca0b"

      def install
        bin.install "yor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.168/yor_0.1.168_linux_arm64.tar.gz"
      sha256 "d4e10da8687d78ef5d9c3f51a00bee45c1723c10b83c8a06a93b820d6063f263"

      def install
        bin.install "yor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.168/yor_0.1.168_linux_amd64.tar.gz"
      sha256 "f272da3169f82528ecec9bc44d37a67710f5787841c0c2523f32ee6e1f549ca9"

      def install
        bin.install "yor"
      end
    end
  end

  test do
    system "#{bin}/yor", "--help"
  end
end
