# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yor < Formula
  desc "Extensible auto-tagger for your IaC files"
  homepage "https://www.yor.io"
  version "0.1.154"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.154/yor_0.1.154_darwin_amd64.tar.gz"
      sha256 "5237345f5248a06118c39c4b26f7ffb016aa96c6690aefc725a17599aca1824b"

      def install
        bin.install "yor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.154/yor_0.1.154_darwin_arm64.tar.gz"
      sha256 "cca134365a90483a9f3fa0d3976b6e2168fe84a5902cd510735a7cb1e2515f77"

      def install
        bin.install "yor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.154/yor_0.1.154_linux_amd64.tar.gz"
      sha256 "f1ab27f4d21c753dca466a9d5c838cfb33d71bd54497abb94894148d7f989d5d"

      def install
        bin.install "yor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bridgecrewio/yor/releases/download/0.1.154/yor_0.1.154_linux_arm64.tar.gz"
      sha256 "328588261dc851636a4fad6dfa85de3fe9875365406287744b79f0055ff3dbb0"

      def install
        bin.install "yor"
      end
    end
  end

  test do
    system "#{bin}/yor", "--help"
  end
end
